name: fauna_db_actions
description: Github action for automating Fauna databases.
author: Fauna Labs
branding:
  icon: 'database'
  color: 'purple'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
  fauna-secret-key:
    description: 'Secret key for Fauna DB'
    required: true
  schema-directory:
    required: false
    default: './'
  package-manager:
    description: 'Package manager to use for dependency installation'
    required: true
    default: 'npm'

outputs:
  test-result:
    description: 'The result of the test run'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: |
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          npm install -g pnpm
          pnpm install
        else
          npm install
        fi
      shell: bash

    - name: Install Fauna CLI
      run: npm install -g fauna-shell
      shell: bash

    - name: Push schema to Database
      run: fauna schema push --force --secret ${{ inputs.fauna-secret-key }} --dir ${{ inputs.schema-directory }}
      shell: bash
